# Generated by Django 4.0.3 on 2022-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
