# Generated by Django 4.0.3 on 2022-04-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
