# Generated by Django 4.0.3 on 2022-04-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_categorias_delete_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascotassapp/static/Appvisual/img'),
        ),
    ]
