# Generated by Django 4.0.3 on 2022-05-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotasapp', '0003_categoria_perros_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='mascotaApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('duenio', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Conejos',
        ),
        migrations.DeleteModel(
            name='Gatos',
        ),
        migrations.RemoveField(
            model_name='perros',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Perros',
        ),
    ]
