# Generated by Django 4.0.3 on 2022-05-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
