# Generated by Django 4.0.3 on 2022-05-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_profile_imagen_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
