# Generated by Django 4.0.3 on 2022-05-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='webiste_url',
            new_name='website_url',
        ),
    ]
